### ISSUE TITLE
Add reset functionality

### ISSUE THREAD

**Issue by SkylerJEhly** [SkylerJEhly/chemistry-chef#2]

**Comment by SkylerJEhly** [comment]
using UnityEngine.SceneManagement;
SceneManager.LoadScene (SceneManager.GetActiveScene ().buildIndex);

OR

SceneManager.LoadScene("Scene_Name");

**Comment by Stangroom** [comment]
Created a button as part of the menu a button that resets the scene. Doesnt preserve position in the scene
