### ISSUE TITLE
Make Custom Menu

### ISSUE THREAD

**Issue by SkylerJEhly** [SkylerJEhly/chemistry-chef#3]

**Comment by SkylerJEhly** [comment]
https://www.youtube.com/watch?v=W9mub3CvTvQ

**Comment by Stangroom** [comment]
Half made interactable buttons, not sure whether to have as static or tracking with head movemeny what functionality do we want?

**Comment by SkylerJEhly** [comment]
Added Tutorial and Exit buttons

**Comment by Stangroom** [comment]
More buttons can be added but done for now
