### ISSUE TITLE
Add limitations to where you can teleport

### ISSUE THREAD

**Issue by SkylerJEhly** [SkylerJEhly/chemistry-chef#5]

**Comment by SkylerJEhly** [comment]
This can be done by changing the type of object from "Default" to "Water". A small section of the floor will still need teleport access so what's the best way to split up the plane?

**Comment by Stangroom** [comment]
rectangle that you can teleport to, using layers

**Comment by Stangroom** [comment]
added a plane called teleport area can only teleport inside that area
